### ISSUE TITLE
autogenerate version and help prints wrong name & wrong version

### ISSUE THREAD

**Issue by kod-kristoff** [parasyte/onlyargs#13]
Hi!

First, thanks for a great crate!

But when trying it [here](https://github.com/kod-kristoff/onlyargs-tutorial) I noticed that checking the version returns this:
```
> cargo run -p onlyargs-tutorial-plain -- --version
onlyargs v0.1.2
```
and not as expected `onlyargs-tutorial-plain v0.1.0`.

If `HELP` isn't overriden, then `--help` also fails.

```
> cargo run -p onlyargs-tutorial-plain --release -- --help
   Compiling onlyargs-tutorial-plain v0.1.0
    Finished release [optimized] target(s) in 3.91s
     Running `target/release/onlyargs-tutorial-plain --help`
onlyargs v0.1.2
Obsessively tiny argument parsing

```

When using `onlyargs-derive` the problem only happens for `--version`.

**Comment by parasyte** [comment]
That's because the help and version text is compiled as static strings in the trait: https://github.com/parasyte/onlyargs/blob/f331a2ecea9a64830dd59d0996846bbd857baaed/src/lib.rs#L57-L72 This gives you a fallback when the implementation doesn't provide the help/version text, but it's of course incorrect.

It might be better to remove the fallback and require the impl to provide both strings.

> When using `onlyargs-derive` the problem only happens for `--version`.

This was an oversight, but it's very easy to fix.
